//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Measure_Unit
    {
        public string Class_Code { get; set; }
        public string Measure_Unit { get; set; }
    
        public virtual Class Class { get; set; }
    }
}
