//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Has_Release_Order
    {
        public string Class_Code { get; set; }
        public long Release_Order_Num { get; set; }
        public string Quantity { get; set; }
        public Nullable<System.DateTime> Production_Date { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Release_Order Release_Order { get; set; }
    }
}
