//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class CompanyProjectEntities : DbContext
    {
        public CompanyProjectEntities()
            : base("name=CompanyProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Class> Classes { get; set; }
        public DbSet<Class_Has_Release_Order> Class_Has_Release_Order { get; set; }
        public DbSet<Class_Has_Sale_Order> Class_Has_Sale_Order { get; set; }
        public DbSet<Class_Measure_Unit> Class_Measure_Unit { get; set; }
        public DbSet<Client> Clients { get; set; }
        public DbSet<Release_Order> Release_Order { get; set; }
        public DbSet<Sale_Order> Sale_Order { get; set; }
        public DbSet<Store> Stores { get; set; }
        public DbSet<Supplier> Suppliers { get; set; }
    
        public virtual ObjectResult<Class_Delete_Result> Class_Delete(string cO)
        {
            var cOParameter = cO != null ?
                new ObjectParameter("CO", cO) :
                new ObjectParameter("CO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Delete_Result>("Class_Delete", cOParameter);
        }
    
        public virtual ObjectResult<Class_Has_Release_Order_Delete_Result> Class_Has_Release_Order_Delete(string cCO, Nullable<long> rO)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var rOParameter = rO.HasValue ?
                new ObjectParameter("RO", rO) :
                new ObjectParameter("RO", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Has_Release_Order_Delete_Result>("Class_Has_Release_Order_Delete", cCOParameter, rOParameter);
        }
    
        public virtual ObjectResult<Class_Has_Release_Order_Insert_Result> Class_Has_Release_Order_Insert(string cCO, Nullable<long> rO, string qTY, Nullable<System.DateTime> pRO_D, Nullable<System.DateTime> eXP_D)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var rOParameter = rO.HasValue ?
                new ObjectParameter("RO", rO) :
                new ObjectParameter("RO", typeof(long));
    
            var qTYParameter = qTY != null ?
                new ObjectParameter("QTY", qTY) :
                new ObjectParameter("QTY", typeof(string));
    
            var pRO_DParameter = pRO_D.HasValue ?
                new ObjectParameter("PRO_D", pRO_D) :
                new ObjectParameter("PRO_D", typeof(System.DateTime));
    
            var eXP_DParameter = eXP_D.HasValue ?
                new ObjectParameter("EXP_D", eXP_D) :
                new ObjectParameter("EXP_D", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Has_Release_Order_Insert_Result>("Class_Has_Release_Order_Insert", cCOParameter, rOParameter, qTYParameter, pRO_DParameter, eXP_DParameter);
        }
    
        public virtual ObjectResult<Class_Has_Release_Order_SelectAll_Result> Class_Has_Release_Order_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Has_Release_Order_SelectAll_Result>("Class_Has_Release_Order_SelectAll");
        }
    
        public virtual ObjectResult<Class_Has_Release_Order_SelectBY_Result> Class_Has_Release_Order_SelectBY(string cCO, Nullable<long> rO)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var rOParameter = rO.HasValue ?
                new ObjectParameter("RO", rO) :
                new ObjectParameter("RO", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Has_Release_Order_SelectBY_Result>("Class_Has_Release_Order_SelectBY", cCOParameter, rOParameter);
        }
    
        public virtual ObjectResult<Class_Has_Release_Order_Update_Result> Class_Has_Release_Order_Update(string cCO, Nullable<long> rO, string qTY, Nullable<System.DateTime> pRO_D, Nullable<System.DateTime> eXP_D)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var rOParameter = rO.HasValue ?
                new ObjectParameter("RO", rO) :
                new ObjectParameter("RO", typeof(long));
    
            var qTYParameter = qTY != null ?
                new ObjectParameter("QTY", qTY) :
                new ObjectParameter("QTY", typeof(string));
    
            var pRO_DParameter = pRO_D.HasValue ?
                new ObjectParameter("PRO_D", pRO_D) :
                new ObjectParameter("PRO_D", typeof(System.DateTime));
    
            var eXP_DParameter = eXP_D.HasValue ?
                new ObjectParameter("EXP_D", eXP_D) :
                new ObjectParameter("EXP_D", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Has_Release_Order_Update_Result>("Class_Has_Release_Order_Update", cCOParameter, rOParameter, qTYParameter, pRO_DParameter, eXP_DParameter);
        }
    
        public virtual ObjectResult<Class_Has_Sale_Order_Delete_Result> Class_Has_Sale_Order_Delete(string cCO, string oS)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var oSParameter = oS != null ?
                new ObjectParameter("OS", oS) :
                new ObjectParameter("OS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Has_Sale_Order_Delete_Result>("Class_Has_Sale_Order_Delete", cCOParameter, oSParameter);
        }
    
        public virtual ObjectResult<Class_Has_Sale_Order_Insert_Result> Class_Has_Sale_Order_Insert(string cCO, Nullable<long> oS, string qTY)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var oSParameter = oS.HasValue ?
                new ObjectParameter("OS", oS) :
                new ObjectParameter("OS", typeof(long));
    
            var qTYParameter = qTY != null ?
                new ObjectParameter("QTY", qTY) :
                new ObjectParameter("QTY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Has_Sale_Order_Insert_Result>("Class_Has_Sale_Order_Insert", cCOParameter, oSParameter, qTYParameter);
        }
    
        public virtual ObjectResult<Class_Has_Sale_Order_SelectAll_Result> Class_Has_Sale_Order_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Has_Sale_Order_SelectAll_Result>("Class_Has_Sale_Order_SelectAll");
        }
    
        public virtual ObjectResult<Class_Has_Sale_Order_SelectBY_Result> Class_Has_Sale_Order_SelectBY(string cCO, Nullable<long> oS)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var oSParameter = oS.HasValue ?
                new ObjectParameter("OS", oS) :
                new ObjectParameter("OS", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Has_Sale_Order_SelectBY_Result>("Class_Has_Sale_Order_SelectBY", cCOParameter, oSParameter);
        }
    
        public virtual ObjectResult<Class_Has_Sale_Order_Update_Result> Class_Has_Sale_Order_Update(string cCO, Nullable<long> oS, string qTY)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var oSParameter = oS.HasValue ?
                new ObjectParameter("OS", oS) :
                new ObjectParameter("OS", typeof(long));
    
            var qTYParameter = qTY != null ?
                new ObjectParameter("QTY", qTY) :
                new ObjectParameter("QTY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Has_Sale_Order_Update_Result>("Class_Has_Sale_Order_Update", cCOParameter, oSParameter, qTYParameter);
        }
    
        public virtual ObjectResult<Class_Insert_Result> Class_Insert(string cO, string nA)
        {
            var cOParameter = cO != null ?
                new ObjectParameter("CO", cO) :
                new ObjectParameter("CO", typeof(string));
    
            var nAParameter = nA != null ?
                new ObjectParameter("NA", nA) :
                new ObjectParameter("NA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Insert_Result>("Class_Insert", cOParameter, nAParameter);
        }
    
        public virtual ObjectResult<Class_Measure_Unit_Delete_Result> Class_Measure_Unit_Delete(string cCO)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Measure_Unit_Delete_Result>("Class_Measure_Unit_Delete", cCOParameter);
        }
    
        public virtual ObjectResult<Class_Measure_Unit_Insert_Result> Class_Measure_Unit_Insert(string cCO, string mU)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var mUParameter = mU != null ?
                new ObjectParameter("MU", mU) :
                new ObjectParameter("MU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Measure_Unit_Insert_Result>("Class_Measure_Unit_Insert", cCOParameter, mUParameter);
        }
    
        public virtual ObjectResult<Class_Measure_Unit_SelectAll_Result> Class_Measure_Unit_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Measure_Unit_SelectAll_Result>("Class_Measure_Unit_SelectAll");
        }
    
        public virtual ObjectResult<Class_Measure_Unit_SelectBY_Result> Class_Measure_Unit_SelectBY(string cCO, string mU)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var mUParameter = mU != null ?
                new ObjectParameter("MU", mU) :
                new ObjectParameter("MU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Measure_Unit_SelectBY_Result>("Class_Measure_Unit_SelectBY", cCOParameter, mUParameter);
        }
    
        public virtual ObjectResult<Class_Measure_Unit_Update_Result> Class_Measure_Unit_Update(string cCO, string mU)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var mUParameter = mU != null ?
                new ObjectParameter("MU", mU) :
                new ObjectParameter("MU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Measure_Unit_Update_Result>("Class_Measure_Unit_Update", cCOParameter, mUParameter);
        }
    
        public virtual ObjectResult<Class_SelectAll_Result> Class_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_SelectAll_Result>("Class_SelectAll");
        }
    
        public virtual ObjectResult<Class_SelectBY_Result> Class_SelectBY(string cO)
        {
            var cOParameter = cO != null ?
                new ObjectParameter("CO", cO) :
                new ObjectParameter("CO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_SelectBY_Result>("Class_SelectBY", cOParameter);
        }
    
        public virtual ObjectResult<Class_Store_Delete_Result> Class_Store_Delete(string sN)
        {
            var sNParameter = sN != null ?
                new ObjectParameter("SN", sN) :
                new ObjectParameter("SN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Store_Delete_Result>("Class_Store_Delete", sNParameter);
        }
    
        public virtual ObjectResult<Class_Store_Insert_Result> Class_Store_Insert(string sN, string cCO)
        {
            var sNParameter = sN != null ?
                new ObjectParameter("SN", sN) :
                new ObjectParameter("SN", typeof(string));
    
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Store_Insert_Result>("Class_Store_Insert", sNParameter, cCOParameter);
        }
    
        public virtual ObjectResult<Class_Store_SelectAll_Result> Class_Store_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Store_SelectAll_Result>("Class_Store_SelectAll");
        }
    
        public virtual ObjectResult<Class_Store_SelectBY_Result> Class_Store_SelectBY(string cCO, string sN)
        {
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var sNParameter = sN != null ?
                new ObjectParameter("SN", sN) :
                new ObjectParameter("SN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Store_SelectBY_Result>("Class_Store_SelectBY", cCOParameter, sNParameter);
        }
    
        public virtual ObjectResult<Class_Store_Unit_SelectB_Result> Class_Store_Unit_SelectB(string sN, string cCO)
        {
            var sNParameter = sN != null ?
                new ObjectParameter("SN", sN) :
                new ObjectParameter("SN", typeof(string));
    
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Store_Unit_SelectB_Result>("Class_Store_Unit_SelectB", sNParameter, cCOParameter);
        }
    
        public virtual ObjectResult<Class_Store_Update_Result> Class_Store_Update(string sN, string cCO)
        {
            var sNParameter = sN != null ?
                new ObjectParameter("SN", sN) :
                new ObjectParameter("SN", typeof(string));
    
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Store_Update_Result>("Class_Store_Update", sNParameter, cCOParameter);
        }
    
        public virtual ObjectResult<Class_Update_Result> Class_Update(string cO, string nA)
        {
            var cOParameter = cO != null ?
                new ObjectParameter("CO", cO) :
                new ObjectParameter("CO", typeof(string));
    
            var nAParameter = nA != null ?
                new ObjectParameter("NA", nA) :
                new ObjectParameter("NA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Update_Result>("Class_Update", cOParameter, nAParameter);
        }
    
        public virtual ObjectResult<Client_Delete_Result> Client_Delete(string fAX)
        {
            var fAXParameter = fAX != null ?
                new ObjectParameter("FAX", fAX) :
                new ObjectParameter("FAX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Client_Delete_Result>("Client_Delete", fAXParameter);
        }
    
        public virtual ObjectResult<Client_Insert_Result> Client_Insert(string nA, string tELE, string pHO, string fAX, string mAIL, string sIT)
        {
            var nAParameter = nA != null ?
                new ObjectParameter("NA", nA) :
                new ObjectParameter("NA", typeof(string));
    
            var tELEParameter = tELE != null ?
                new ObjectParameter("TELE", tELE) :
                new ObjectParameter("TELE", typeof(string));
    
            var pHOParameter = pHO != null ?
                new ObjectParameter("PHO", pHO) :
                new ObjectParameter("PHO", typeof(string));
    
            var fAXParameter = fAX != null ?
                new ObjectParameter("FAX", fAX) :
                new ObjectParameter("FAX", typeof(string));
    
            var mAILParameter = mAIL != null ?
                new ObjectParameter("MAIL", mAIL) :
                new ObjectParameter("MAIL", typeof(string));
    
            var sITParameter = sIT != null ?
                new ObjectParameter("SIT", sIT) :
                new ObjectParameter("SIT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Client_Insert_Result>("Client_Insert", nAParameter, tELEParameter, pHOParameter, fAXParameter, mAILParameter, sITParameter);
        }
    
        public virtual ObjectResult<Client_SelectAll_Result> Client_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Client_SelectAll_Result>("Client_SelectAll");
        }
    
        public virtual ObjectResult<Client_SelectBY_Result> Client_SelectBY(string fAX)
        {
            var fAXParameter = fAX != null ?
                new ObjectParameter("FAX", fAX) :
                new ObjectParameter("FAX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Client_SelectBY_Result>("Client_SelectBY", fAXParameter);
        }
    
        public virtual ObjectResult<Client_Update_Result> Client_Update(string nA, string tELE, string pHO, string fAX, string mAIL, string sIT)
        {
            var nAParameter = nA != null ?
                new ObjectParameter("NA", nA) :
                new ObjectParameter("NA", typeof(string));
    
            var tELEParameter = tELE != null ?
                new ObjectParameter("TELE", tELE) :
                new ObjectParameter("TELE", typeof(string));
    
            var pHOParameter = pHO != null ?
                new ObjectParameter("PHO", pHO) :
                new ObjectParameter("PHO", typeof(string));
    
            var fAXParameter = fAX != null ?
                new ObjectParameter("FAX", fAX) :
                new ObjectParameter("FAX", typeof(string));
    
            var mAILParameter = mAIL != null ?
                new ObjectParameter("MAIL", mAIL) :
                new ObjectParameter("MAIL", typeof(string));
    
            var sITParameter = sIT != null ?
                new ObjectParameter("SIT", sIT) :
                new ObjectParameter("SIT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Client_Update_Result>("Client_Update", nAParameter, tELEParameter, pHOParameter, fAXParameter, mAILParameter, sITParameter);
        }
    
        public virtual int CommonBetweenRelease_Insert(string sTRNAM, Nullable<long> nUM, Nullable<System.DateTime> dAT, string cLSNAM, string qUAN, string sUPNAM, Nullable<System.DateTime> pROD, Nullable<System.DateTime> eXEP)
        {
            var sTRNAMParameter = sTRNAM != null ?
                new ObjectParameter("STRNAM", sTRNAM) :
                new ObjectParameter("STRNAM", typeof(string));
    
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            var dATParameter = dAT.HasValue ?
                new ObjectParameter("DAT", dAT) :
                new ObjectParameter("DAT", typeof(System.DateTime));
    
            var cLSNAMParameter = cLSNAM != null ?
                new ObjectParameter("CLSNAM", cLSNAM) :
                new ObjectParameter("CLSNAM", typeof(string));
    
            var qUANParameter = qUAN != null ?
                new ObjectParameter("QUAN", qUAN) :
                new ObjectParameter("QUAN", typeof(string));
    
            var sUPNAMParameter = sUPNAM != null ?
                new ObjectParameter("SUPNAM", sUPNAM) :
                new ObjectParameter("SUPNAM", typeof(string));
    
            var pRODParameter = pROD.HasValue ?
                new ObjectParameter("PROD", pROD) :
                new ObjectParameter("PROD", typeof(System.DateTime));
    
            var eXEPParameter = eXEP.HasValue ?
                new ObjectParameter("EXEP", eXEP) :
                new ObjectParameter("EXEP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CommonBetweenRelease_Insert", sTRNAMParameter, nUMParameter, dATParameter, cLSNAMParameter, qUANParameter, sUPNAMParameter, pRODParameter, eXEPParameter);
        }
    
        public virtual ObjectResult<CommonBetweenRelease_SelectAll_Result> CommonBetweenRelease_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CommonBetweenRelease_SelectAll_Result>("CommonBetweenRelease_SelectAll");
        }
    
        public virtual int CommonBetweenRelease_Update2(string sTRN, Nullable<long> nUM, Nullable<System.DateTime> dAT, string cLSNAM, string qUAN, string sUPNAM, Nullable<System.DateTime> pROD, Nullable<System.DateTime> eXP)
        {
            var sTRNParameter = sTRN != null ?
                new ObjectParameter("STRN", sTRN) :
                new ObjectParameter("STRN", typeof(string));
    
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            var dATParameter = dAT.HasValue ?
                new ObjectParameter("DAT", dAT) :
                new ObjectParameter("DAT", typeof(System.DateTime));
    
            var cLSNAMParameter = cLSNAM != null ?
                new ObjectParameter("CLSNAM", cLSNAM) :
                new ObjectParameter("CLSNAM", typeof(string));
    
            var qUANParameter = qUAN != null ?
                new ObjectParameter("QUAN", qUAN) :
                new ObjectParameter("QUAN", typeof(string));
    
            var sUPNAMParameter = sUPNAM != null ?
                new ObjectParameter("SUPNAM", sUPNAM) :
                new ObjectParameter("SUPNAM", typeof(string));
    
            var pRODParameter = pROD.HasValue ?
                new ObjectParameter("PROD", pROD) :
                new ObjectParameter("PROD", typeof(System.DateTime));
    
            var eXPParameter = eXP.HasValue ?
                new ObjectParameter("EXP", eXP) :
                new ObjectParameter("EXP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CommonBetweenRelease_Update2", sTRNParameter, nUMParameter, dATParameter, cLSNAMParameter, qUANParameter, sUPNAMParameter, pRODParameter, eXPParameter);
        }
    
        public virtual int CommonBetweenRelease_UpdateAll(string sTRN, Nullable<long> nUM, Nullable<System.DateTime> dAT, string cLSNAM, string qUAN, string sUPNAM, Nullable<System.DateTime> pROD, Nullable<System.DateTime> eXP, string cCO, string sUPFAX)
        {
            var sTRNParameter = sTRN != null ?
                new ObjectParameter("STRN", sTRN) :
                new ObjectParameter("STRN", typeof(string));
    
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            var dATParameter = dAT.HasValue ?
                new ObjectParameter("DAT", dAT) :
                new ObjectParameter("DAT", typeof(System.DateTime));
    
            var cLSNAMParameter = cLSNAM != null ?
                new ObjectParameter("CLSNAM", cLSNAM) :
                new ObjectParameter("CLSNAM", typeof(string));
    
            var qUANParameter = qUAN != null ?
                new ObjectParameter("QUAN", qUAN) :
                new ObjectParameter("QUAN", typeof(string));
    
            var sUPNAMParameter = sUPNAM != null ?
                new ObjectParameter("SUPNAM", sUPNAM) :
                new ObjectParameter("SUPNAM", typeof(string));
    
            var pRODParameter = pROD.HasValue ?
                new ObjectParameter("PROD", pROD) :
                new ObjectParameter("PROD", typeof(System.DateTime));
    
            var eXPParameter = eXP.HasValue ?
                new ObjectParameter("EXP", eXP) :
                new ObjectParameter("EXP", typeof(System.DateTime));
    
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var sUPFAXParameter = sUPFAX != null ?
                new ObjectParameter("SUPFAX", sUPFAX) :
                new ObjectParameter("SUPFAX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CommonBetweenRelease_UpdateAll", sTRNParameter, nUMParameter, dATParameter, cLSNAMParameter, qUANParameter, sUPNAMParameter, pRODParameter, eXPParameter, cCOParameter, sUPFAXParameter);
        }
    
        public virtual int CommonBetweenSale_Insert(string sTRNAM, Nullable<long> nUM, Nullable<System.DateTime> dAT, string cLSNAM, string cLINAM, string qUANTITY)
        {
            var sTRNAMParameter = sTRNAM != null ?
                new ObjectParameter("STRNAM", sTRNAM) :
                new ObjectParameter("STRNAM", typeof(string));
    
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            var dATParameter = dAT.HasValue ?
                new ObjectParameter("DAT", dAT) :
                new ObjectParameter("DAT", typeof(System.DateTime));
    
            var cLSNAMParameter = cLSNAM != null ?
                new ObjectParameter("CLSNAM", cLSNAM) :
                new ObjectParameter("CLSNAM", typeof(string));
    
            var cLINAMParameter = cLINAM != null ?
                new ObjectParameter("CLINAM", cLINAM) :
                new ObjectParameter("CLINAM", typeof(string));
    
            var qUANTITYParameter = qUANTITY != null ?
                new ObjectParameter("QUANTITY", qUANTITY) :
                new ObjectParameter("QUANTITY", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CommonBetweenSale_Insert", sTRNAMParameter, nUMParameter, dATParameter, cLSNAMParameter, cLINAMParameter, qUANTITYParameter);
        }
    
        public virtual ObjectResult<CommonBetweenSale_SelectAll_Result> CommonBetweenSale_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CommonBetweenSale_SelectAll_Result>("CommonBetweenSale_SelectAll");
        }
    
        public virtual int CommonBetweenSale_Update(string sTRNAM, Nullable<long> nUM, Nullable<System.DateTime> dAT, string cLSNAM, string cLINAM, string qUAN, string cCO, string cLIFAX)
        {
            var sTRNAMParameter = sTRNAM != null ?
                new ObjectParameter("STRNAM", sTRNAM) :
                new ObjectParameter("STRNAM", typeof(string));
    
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            var dATParameter = dAT.HasValue ?
                new ObjectParameter("DAT", dAT) :
                new ObjectParameter("DAT", typeof(System.DateTime));
    
            var cLSNAMParameter = cLSNAM != null ?
                new ObjectParameter("CLSNAM", cLSNAM) :
                new ObjectParameter("CLSNAM", typeof(string));
    
            var cLINAMParameter = cLINAM != null ?
                new ObjectParameter("CLINAM", cLINAM) :
                new ObjectParameter("CLINAM", typeof(string));
    
            var qUANParameter = qUAN != null ?
                new ObjectParameter("QUAN", qUAN) :
                new ObjectParameter("QUAN", typeof(string));
    
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var cLIFAXParameter = cLIFAX != null ?
                new ObjectParameter("CLIFAX", cLIFAX) :
                new ObjectParameter("CLIFAX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CommonBetweenSale_Update", sTRNAMParameter, nUMParameter, dATParameter, cLSNAMParameter, cLINAMParameter, qUANParameter, cCOParameter, cLIFAXParameter);
        }
    
        public virtual int CommonBetweenSale_Update2(string sTRNAM, Nullable<long> nUM, Nullable<System.DateTime> dAT, string cLSNAM, string cLINAM, string qUAN)
        {
            var sTRNAMParameter = sTRNAM != null ?
                new ObjectParameter("STRNAM", sTRNAM) :
                new ObjectParameter("STRNAM", typeof(string));
    
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            var dATParameter = dAT.HasValue ?
                new ObjectParameter("DAT", dAT) :
                new ObjectParameter("DAT", typeof(System.DateTime));
    
            var cLSNAMParameter = cLSNAM != null ?
                new ObjectParameter("CLSNAM", cLSNAM) :
                new ObjectParameter("CLSNAM", typeof(string));
    
            var cLINAMParameter = cLINAM != null ?
                new ObjectParameter("CLINAM", cLINAM) :
                new ObjectParameter("CLINAM", typeof(string));
    
            var qUANParameter = qUAN != null ?
                new ObjectParameter("QUAN", qUAN) :
                new ObjectParameter("QUAN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CommonBetweenSale_Update2", sTRNAMParameter, nUMParameter, dATParameter, cLSNAMParameter, cLINAMParameter, qUANParameter);
        }
    
        public virtual ObjectResult<Release_Order_Delete_Result> Release_Order_Delete(Nullable<long> nUM)
        {
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Release_Order_Delete_Result>("Release_Order_Delete", nUMParameter);
        }
    
        public virtual ObjectResult<Release_Order_Insert_Result> Release_Order_Insert(Nullable<long> nUM, string sN, Nullable<System.DateTime> dT, string sF)
        {
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            var sNParameter = sN != null ?
                new ObjectParameter("SN", sN) :
                new ObjectParameter("SN", typeof(string));
    
            var dTParameter = dT.HasValue ?
                new ObjectParameter("DT", dT) :
                new ObjectParameter("DT", typeof(System.DateTime));
    
            var sFParameter = sF != null ?
                new ObjectParameter("SF", sF) :
                new ObjectParameter("SF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Release_Order_Insert_Result>("Release_Order_Insert", nUMParameter, sNParameter, dTParameter, sFParameter);
        }
    
        public virtual ObjectResult<Release_Order_SelectAll_Result> Release_Order_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Release_Order_SelectAll_Result>("Release_Order_SelectAll");
        }
    
        public virtual ObjectResult<Release_Order_SelectBY_Result> Release_Order_SelectBY(Nullable<long> nUM)
        {
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Release_Order_SelectBY_Result>("Release_Order_SelectBY", nUMParameter);
        }
    
        public virtual ObjectResult<Release_Order_Update_Result> Release_Order_Update(Nullable<long> nUM, string sN, Nullable<System.DateTime> dT, string sF)
        {
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            var sNParameter = sN != null ?
                new ObjectParameter("SN", sN) :
                new ObjectParameter("SN", typeof(string));
    
            var dTParameter = dT.HasValue ?
                new ObjectParameter("DT", dT) :
                new ObjectParameter("DT", typeof(System.DateTime));
    
            var sFParameter = sF != null ?
                new ObjectParameter("SF", sF) :
                new ObjectParameter("SF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Release_Order_Update_Result>("Release_Order_Update", nUMParameter, sNParameter, dTParameter, sFParameter);
        }
    
        public virtual ObjectResult<Sale_Order_Delete_Result> Sale_Order_Delete(Nullable<long> nUM)
        {
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sale_Order_Delete_Result>("Sale_Order_Delete", nUMParameter);
        }
    
        public virtual ObjectResult<Sale_Order_Insert_Result> Sale_Order_Insert(Nullable<long> nUM, string sN, Nullable<System.DateTime> dT, string cF)
        {
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            var sNParameter = sN != null ?
                new ObjectParameter("SN", sN) :
                new ObjectParameter("SN", typeof(string));
    
            var dTParameter = dT.HasValue ?
                new ObjectParameter("DT", dT) :
                new ObjectParameter("DT", typeof(System.DateTime));
    
            var cFParameter = cF != null ?
                new ObjectParameter("CF", cF) :
                new ObjectParameter("CF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sale_Order_Insert_Result>("Sale_Order_Insert", nUMParameter, sNParameter, dTParameter, cFParameter);
        }
    
        public virtual ObjectResult<Sale_Order_SelectAll_Result> Sale_Order_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sale_Order_SelectAll_Result>("Sale_Order_SelectAll");
        }
    
        public virtual ObjectResult<Sale_Order_SelectBY_Result> Sale_Order_SelectBY(Nullable<long> nUM)
        {
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sale_Order_SelectBY_Result>("Sale_Order_SelectBY", nUMParameter);
        }
    
        public virtual ObjectResult<Sale_Order_Update_Result> Sale_Order_Update(Nullable<long> nUM, string sN, Nullable<System.DateTime> dT, string cF)
        {
            var nUMParameter = nUM.HasValue ?
                new ObjectParameter("NUM", nUM) :
                new ObjectParameter("NUM", typeof(long));
    
            var sNParameter = sN != null ?
                new ObjectParameter("SN", sN) :
                new ObjectParameter("SN", typeof(string));
    
            var dTParameter = dT.HasValue ?
                new ObjectParameter("DT", dT) :
                new ObjectParameter("DT", typeof(System.DateTime));
    
            var cFParameter = cF != null ?
                new ObjectParameter("CF", cF) :
                new ObjectParameter("CF", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Sale_Order_Update_Result>("Sale_Order_Update", nUMParameter, sNParameter, dTParameter, cFParameter);
        }
    
        public virtual ObjectResult<ShowClass_Result> ShowClass(string sTN)
        {
            var sTNParameter = sTN != null ?
                new ObjectParameter("STN", sTN) :
                new ObjectParameter("STN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ShowClass_Result>("ShowClass", sTNParameter);
        }
    
        public virtual ObjectResult<Store_Delete_Result> Store_Delete(string nA)
        {
            var nAParameter = nA != null ?
                new ObjectParameter("NA", nA) :
                new ObjectParameter("NA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Store_Delete_Result>("Store_Delete", nAParameter);
        }
    
        public virtual ObjectResult<Store_Insert_Result> Store_Insert(string nA, string aDRS, string mNGR)
        {
            var nAParameter = nA != null ?
                new ObjectParameter("NA", nA) :
                new ObjectParameter("NA", typeof(string));
    
            var aDRSParameter = aDRS != null ?
                new ObjectParameter("ADRS", aDRS) :
                new ObjectParameter("ADRS", typeof(string));
    
            var mNGRParameter = mNGR != null ?
                new ObjectParameter("MNGR", mNGR) :
                new ObjectParameter("MNGR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Store_Insert_Result>("Store_Insert", nAParameter, aDRSParameter, mNGRParameter);
        }
    
        public virtual ObjectResult<Store_SelectAll_Result> Store_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Store_SelectAll_Result>("Store_SelectAll");
        }
    
        public virtual ObjectResult<Store_SelectBY_Result> Store_SelectBY(string nA)
        {
            var nAParameter = nA != null ?
                new ObjectParameter("NA", nA) :
                new ObjectParameter("NA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Store_SelectBY_Result>("Store_SelectBY", nAParameter);
        }
    
        public virtual ObjectResult<Store_Update_Result> Store_Update(string nA, string aDRS, string mNGR)
        {
            var nAParameter = nA != null ?
                new ObjectParameter("NA", nA) :
                new ObjectParameter("NA", typeof(string));
    
            var aDRSParameter = aDRS != null ?
                new ObjectParameter("ADRS", aDRS) :
                new ObjectParameter("ADRS", typeof(string));
    
            var mNGRParameter = mNGR != null ?
                new ObjectParameter("MNGR", mNGR) :
                new ObjectParameter("MNGR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Store_Update_Result>("Store_Update", nAParameter, aDRSParameter, mNGRParameter);
        }
    
        public virtual ObjectResult<Supplier_Delete_Result> Supplier_Delete(string fAX)
        {
            var fAXParameter = fAX != null ?
                new ObjectParameter("FAX", fAX) :
                new ObjectParameter("FAX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Supplier_Delete_Result>("Supplier_Delete", fAXParameter);
        }
    
        public virtual ObjectResult<Supplier_Insert_Result> Supplier_Insert(string nA, string tELE, string pHO, string fAX, string mAIL, string sIT)
        {
            var nAParameter = nA != null ?
                new ObjectParameter("NA", nA) :
                new ObjectParameter("NA", typeof(string));
    
            var tELEParameter = tELE != null ?
                new ObjectParameter("TELE", tELE) :
                new ObjectParameter("TELE", typeof(string));
    
            var pHOParameter = pHO != null ?
                new ObjectParameter("PHO", pHO) :
                new ObjectParameter("PHO", typeof(string));
    
            var fAXParameter = fAX != null ?
                new ObjectParameter("FAX", fAX) :
                new ObjectParameter("FAX", typeof(string));
    
            var mAILParameter = mAIL != null ?
                new ObjectParameter("MAIL", mAIL) :
                new ObjectParameter("MAIL", typeof(string));
    
            var sITParameter = sIT != null ?
                new ObjectParameter("SIT", sIT) :
                new ObjectParameter("SIT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Supplier_Insert_Result>("Supplier_Insert", nAParameter, tELEParameter, pHOParameter, fAXParameter, mAILParameter, sITParameter);
        }
    
        public virtual ObjectResult<Supplier_SelectAll_Result> Supplier_SelectAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Supplier_SelectAll_Result>("Supplier_SelectAll");
        }
    
        public virtual ObjectResult<Supplier_SelectBY_Result> Supplier_SelectBY(string fAX)
        {
            var fAXParameter = fAX != null ?
                new ObjectParameter("FAX", fAX) :
                new ObjectParameter("FAX", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Supplier_SelectBY_Result>("Supplier_SelectBY", fAXParameter);
        }
    
        public virtual ObjectResult<Supplier_Update_Result> Supplier_Update(string nA, string tELE, string pHO, string fAX, string mAIL, string sIT)
        {
            var nAParameter = nA != null ?
                new ObjectParameter("NA", nA) :
                new ObjectParameter("NA", typeof(string));
    
            var tELEParameter = tELE != null ?
                new ObjectParameter("TELE", tELE) :
                new ObjectParameter("TELE", typeof(string));
    
            var pHOParameter = pHO != null ?
                new ObjectParameter("PHO", pHO) :
                new ObjectParameter("PHO", typeof(string));
    
            var fAXParameter = fAX != null ?
                new ObjectParameter("FAX", fAX) :
                new ObjectParameter("FAX", typeof(string));
    
            var mAILParameter = mAIL != null ?
                new ObjectParameter("MAIL", mAIL) :
                new ObjectParameter("MAIL", typeof(string));
    
            var sITParameter = sIT != null ?
                new ObjectParameter("SIT", sIT) :
                new ObjectParameter("SIT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Supplier_Update_Result>("Supplier_Update", nAParameter, tELEParameter, pHOParameter, fAXParameter, mAILParameter, sITParameter);
        }
    
        public virtual ObjectResult<Transfer_Classes_Result> Transfer_Classes(Nullable<long> oNUM, string cCO, string fST, string tST, string qUAN, string sUPNAM, Nullable<System.DateTime> pROD, Nullable<System.DateTime> eXP)
        {
            var oNUMParameter = oNUM.HasValue ?
                new ObjectParameter("ONUM", oNUM) :
                new ObjectParameter("ONUM", typeof(long));
    
            var cCOParameter = cCO != null ?
                new ObjectParameter("CCO", cCO) :
                new ObjectParameter("CCO", typeof(string));
    
            var fSTParameter = fST != null ?
                new ObjectParameter("FST", fST) :
                new ObjectParameter("FST", typeof(string));
    
            var tSTParameter = tST != null ?
                new ObjectParameter("TST", tST) :
                new ObjectParameter("TST", typeof(string));
    
            var qUANParameter = qUAN != null ?
                new ObjectParameter("QUAN", qUAN) :
                new ObjectParameter("QUAN", typeof(string));
    
            var sUPNAMParameter = sUPNAM != null ?
                new ObjectParameter("SUPNAM", sUPNAM) :
                new ObjectParameter("SUPNAM", typeof(string));
    
            var pRODParameter = pROD.HasValue ?
                new ObjectParameter("PROD", pROD) :
                new ObjectParameter("PROD", typeof(System.DateTime));
    
            var eXPParameter = eXP.HasValue ?
                new ObjectParameter("EXP", eXP) :
                new ObjectParameter("EXP", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Transfer_Classes_Result>("Transfer_Classes", oNUMParameter, cCOParameter, fSTParameter, tSTParameter, qUANParameter, sUPNAMParameter, pRODParameter, eXPParameter);
        }
    
        public virtual ObjectResult<Store_Report2_Result> Store_Report2(Nullable<System.DateTime> dAT, Nullable<System.DateTime> dAT1)
        {
            var dATParameter = dAT.HasValue ?
                new ObjectParameter("DAT", dAT) :
                new ObjectParameter("DAT", typeof(System.DateTime));
    
            var dAT1Parameter = dAT1.HasValue ?
                new ObjectParameter("DAT1", dAT1) :
                new ObjectParameter("DAT1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Store_Report2_Result>("Store_Report2", dATParameter, dAT1Parameter);
        }
    
        public virtual ObjectResult<Class_Report_Result> Class_Report()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Report_Result>("Class_Report");
        }
    
        public virtual ObjectResult<Class_Report1_Result> Class_Report1(string sTRNM, Nullable<System.DateTime> dAT, Nullable<System.DateTime> dAT1)
        {
            var sTRNMParameter = sTRNM != null ?
                new ObjectParameter("STRNM", sTRNM) :
                new ObjectParameter("STRNM", typeof(string));
    
            var dATParameter = dAT.HasValue ?
                new ObjectParameter("DAT", dAT) :
                new ObjectParameter("DAT", typeof(System.DateTime));
    
            var dAT1Parameter = dAT1.HasValue ?
                new ObjectParameter("DAT1", dAT1) :
                new ObjectParameter("DAT1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Class_Report1_Result>("Class_Report1", sTRNMParameter, dATParameter, dAT1Parameter);
        }
    
        public virtual ObjectResult<EXPDA_Result> EXPDA(Nullable<long> tIME, Nullable<System.DateTime> dAT, Nullable<System.DateTime> dAT1)
        {
            var tIMEParameter = tIME.HasValue ?
                new ObjectParameter("TIME", tIME) :
                new ObjectParameter("TIME", typeof(long));
    
            var dATParameter = dAT.HasValue ?
                new ObjectParameter("DAT", dAT) :
                new ObjectParameter("DAT", typeof(System.DateTime));
    
            var dAT1Parameter = dAT1.HasValue ?
                new ObjectParameter("DAT1", dAT1) :
                new ObjectParameter("DAT1", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EXPDA_Result>("EXPDA", tIMEParameter, dATParameter, dAT1Parameter);
        }
    
        public virtual ObjectResult<EXPDA1_Result> EXPDA1(Nullable<long> tIME)
        {
            var tIMEParameter = tIME.HasValue ?
                new ObjectParameter("TIME", tIME) :
                new ObjectParameter("TIME", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EXPDA1_Result>("EXPDA1", tIMEParameter);
        }
    }
}
