//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Release_Order = new HashSet<Release_Order>();
            this.Sale_Order = new HashSet<Sale_Order>();
            this.Classes = new HashSet<Class>();
        }
    
        public string C_Name { get; set; }
        public string C_Address { get; set; }
        public string Manager { get; set; }
    
        public virtual ICollection<Release_Order> Release_Order { get; set; }
        public virtual ICollection<Sale_Order> Sale_Order { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
    }
}
